/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/postings/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Posting Lookup */
        post: operations["posting_lookup_api_postings_lookup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/postings/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Postings */
        post: operations["query_postings_api_postings_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/postings/{posting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Posting */
        get: operations["posting_api_postings__posting_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_api_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Stream */
        post: operations["search_stream_api_search_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppliedFilter */
        AppliedFilter: {
            /** Field */
            field: string;
            /** Label */
            label: string;
            /** Note */
            note?: string | null;
        };
        /** BestMatchData */
        BestMatchData: {
            /** Corpus Size */
            corpus_size: number;
            /** Filters Applied */
            filters_applied: components["schemas"]["AppliedFilter"][];
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["BestMatchPosting"][];
            /** Terms */
            terms: string[];
            /** Trace */
            trace: components["schemas"]["TraceNode"][];
        };
        /** BestMatchPosting */
        BestMatchPosting: {
            /** Company */
            company: string;
            evidence?: components["schemas"]["RankingEvidence"] | null;
            /** First Seen At */
            first_seen_at?: string | null;
            /** Id */
            id: string;
            /** Location */
            location?: string | null;
            /** Posted At */
            posted_at?: string | null;
            remote_policy?: components["schemas"]["RemotePolicy"] | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Salary Min */
            salary_min?: number | null;
            /** Score */
            score: number;
            seniority?: components["schemas"]["PostingSeniority"] | null;
            source: components["schemas"]["SourceId"];
            /** Stack */
            stack?: string[];
            /** Title */
            title: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Years Required */
            years_required?: number | null;
        };
        /** BestMatchRequest */
        BestMatchRequest: {
            filters?: components["schemas"]["PostingFilters"];
            /**
             * Profile Text
             * @default
             */
            profile_text: string;
            /**
             * Query
             * @default
             */
            query: string;
        };
        /** CatalogueQueryRequest */
        CatalogueQueryRequest: {
            filters?: components["schemas"]["PostingFilters"];
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Query
             * @default
             */
            query: string;
            /** @default newest */
            sort: components["schemas"]["CatalogueSort"];
        };
        /**
         * CatalogueSort
         * @enum {string}
         */
        CatalogueSort: "newest" | "salary";
        /** ErrorBody */
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "EMPTY_SEARCH" | "INVALID_REQUEST" | "POSTING_NOT_FOUND" | "VALIDATION_ERROR" | "RATE_LIMITED" | "SEARCH_UNAVAILABLE" | "CATALOGUE_UNAVAILABLE" | "INTERNAL_ERROR";
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /**
         * EvidenceField
         * @enum {string}
         */
        EvidenceField: "title" | "company" | "location" | "stack" | "requirements" | "responsibilities" | "description";
        /** LiteralHit */
        LiteralHit: {
            /** Fields */
            fields: components["schemas"]["EvidenceField"][];
            /** Term */
            term: string;
        };
        /** MetaData */
        MetaData: {
            /** Corpus Size */
            corpus_size: number;
            /** Retrieval */
            retrieval: string;
            /** Source Counts */
            source_counts: components["schemas"]["SourceCountData"][];
            /** Sources */
            sources: components["schemas"]["SourceId"][];
        };
        /** PaginationMeta */
        PaginationMeta: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Items */
            total_items: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * PostedWithin
         * @enum {string}
         */
        PostedWithin: "24h" | "7d" | "30d";
        /** PostingDetail */
        PostingDetail: {
            /** Company */
            company: string;
            /** Delisted At */
            delisted_at?: string | null;
            /** Description */
            description?: string | null;
            /** First Seen At */
            first_seen_at?: string | null;
            /** Id */
            id: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Location */
            location?: string | null;
            /** Posted At */
            posted_at?: string | null;
            remote_policy?: components["schemas"]["RemotePolicy"] | null;
            /** Requirements */
            requirements?: string | null;
            /** Responsibilities */
            responsibilities?: string | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Salary Min */
            salary_min?: number | null;
            seniority?: components["schemas"]["PostingSeniority"] | null;
            source: components["schemas"]["SourceId"];
            /** Stack */
            stack?: string[];
            /** Title */
            title: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Years Required */
            years_required?: number | null;
        };
        /** PostingFilters */
        PostingFilters: {
            /** Experience Years */
            experience_years?: number | null;
            /**
             * Include Undisclosed Salary
             * @default false
             */
            include_undisclosed_salary: boolean;
            /** Min Salary */
            min_salary?: number | null;
            posted_within?: components["schemas"]["PostedWithin"] | null;
            /** Remote Policy */
            remote_policy?: components["schemas"]["RemoteFilter"][];
            /** Seniority */
            seniority?: components["schemas"]["SeniorityFilter"][];
            /** Source */
            source?: components["schemas"]["SourceId"][];
        };
        /** PostingLookupRequest */
        PostingLookupRequest: {
            /** Ids */
            ids: string[];
        };
        /**
         * PostingSection
         * @enum {string}
         */
        PostingSection: "requirements" | "responsibilities" | "description";
        /**
         * PostingSeniority
         * @enum {string}
         */
        PostingSeniority: "intern" | "junior" | "mid" | "senior" | "lead" | "principal" | "unknown";
        /** PostingSummary */
        PostingSummary: {
            /** Company */
            company: string;
            /** First Seen At */
            first_seen_at?: string | null;
            /** Id */
            id: string;
            /** Location */
            location?: string | null;
            /** Posted At */
            posted_at?: string | null;
            remote_policy?: components["schemas"]["RemotePolicy"] | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Salary Min */
            salary_min?: number | null;
            seniority?: components["schemas"]["PostingSeniority"] | null;
            source: components["schemas"]["SourceId"];
            /** Stack */
            stack?: string[];
            /** Title */
            title: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Years Required */
            years_required?: number | null;
        };
        /** RankingEvidence */
        RankingEvidence: {
            /** Literal Hits */
            literal_hits?: components["schemas"]["LiteralHit"][];
            /** Retrieved Sections */
            retrieved_sections?: components["schemas"]["PostingSection"][];
        };
        /**
         * RankingStage
         * @enum {string}
         */
        RankingStage: "rewrite" | "filter" | "retrieve" | "group" | "rerank";
        /**
         * RemoteFilter
         * @enum {string}
         */
        RemoteFilter: "remote" | "hybrid" | "onsite";
        /**
         * RemotePolicy
         * @enum {string}
         */
        RemotePolicy: "remote" | "hybrid" | "onsite" | "unknown";
        /** ResolvedPosting */
        ResolvedPosting: {
            /** Company */
            company: string;
            /** Delisted At */
            delisted_at?: string | null;
            /** First Seen At */
            first_seen_at?: string | null;
            /** Id */
            id: string;
            /** Location */
            location?: string | null;
            /** Posted At */
            posted_at?: string | null;
            remote_policy?: components["schemas"]["RemotePolicy"] | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Salary Min */
            salary_min?: number | null;
            seniority?: components["schemas"]["PostingSeniority"] | null;
            source: components["schemas"]["SourceId"];
            /** Stack */
            stack?: string[];
            /** Title */
            title: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Years Required */
            years_required?: number | null;
        };
        /** ResponseMeta */
        ResponseMeta: {
            pagination?: components["schemas"]["PaginationMeta"] | null;
            /** Request Id */
            request_id: string;
            /** Took Ms */
            took_ms?: number | null;
        };
        /** SearchCompleted */
        SearchCompleted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "search.completed";
            /** Request Id */
            request_id: string;
            snapshot: components["schemas"]["BestMatchData"];
            /** Took Ms */
            took_ms: number;
        };
        /** SearchFailed */
        SearchFailed: {
            error: components["schemas"]["ErrorBody"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "search.failed";
            /** Request Id */
            request_id: string;
        };
        /** SearchStarted */
        SearchStarted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "search.started";
            /** Request Id */
            request_id: string;
        };
        /**
         * SeniorityFilter
         * @enum {string}
         */
        SeniorityFilter: "intern" | "junior" | "mid" | "senior" | "lead" | "principal";
        /** SourceCountData */
        SourceCountData: {
            /** Count */
            count: number;
            source: components["schemas"]["SourceId"];
        };
        /**
         * SourceId
         * @enum {string}
         */
        SourceId: "greenhouse" | "ashby" | "lever" | "djinni" | "dou" | "jobico" | "linkedin";
        /** StageCompleted */
        StageCompleted: {
            /** Detail */
            detail: string;
            /** Duration Ms */
            duration_ms: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "stage.completed";
            /** Item Count */
            item_count: number;
            /** Ordinal */
            ordinal: number;
            /** Request Id */
            request_id: string;
            stage: components["schemas"]["RankingStage"];
            status: components["schemas"]["TraceStatus"];
        };
        /** StageStarted */
        StageStarted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "stage.started";
            /** Ordinal */
            ordinal: number;
            /** Request Id */
            request_id: string;
            stage: components["schemas"]["RankingStage"];
        };
        /** SuccessResponse[BestMatchData] */
        SuccessResponse_BestMatchData_: {
            data: components["schemas"]["BestMatchData"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** SuccessResponse[MetaData] */
        SuccessResponse_MetaData_: {
            data: components["schemas"]["MetaData"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** SuccessResponse[PostingDetail] */
        SuccessResponse_PostingDetail_: {
            data: components["schemas"]["PostingDetail"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** SuccessResponse[list[PostingSummary]] */
        SuccessResponse_list_PostingSummary__: {
            /** Data */
            data: components["schemas"]["PostingSummary"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** SuccessResponse[list[ResolvedPosting]] */
        SuccessResponse_list_ResolvedPosting__: {
            /** Data */
            data: components["schemas"]["ResolvedPosting"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** TraceNode */
        TraceNode: {
            /** Count */
            count: number;
            /** Detail */
            detail: string;
            /** Duration Ms */
            duration_ms: number;
            node: components["schemas"]["RankingStage"];
            status: components["schemas"]["TraceStatus"];
        };
        /**
         * TraceStatus
         * @enum {string}
         */
        TraceStatus: "ran" | "skipped";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_MetaData_"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    posting_lookup_api_postings_lookup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostingLookupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_list_ResolvedPosting__"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    query_postings_api_postings_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogueQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_list_PostingSummary__"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    posting_api_postings__posting_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                posting_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_PostingDetail_"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_api_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BestMatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_BestMatchData_"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_stream_api_search_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BestMatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error envelope */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error envelope */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
